# Generated by Django 2.1.4 on 2018-12-29 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[(1, 'Витрата'), (2, 'Прибуток')], default=1, max_length=1)),
                ('money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('about', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bubbleapp.Category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
    ]
