# Generated by Django 2.1.4 on 2018-12-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='subcategory',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bubbleapp.Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation_type',
            field=models.DecimalField(choices=[(1, 'Витрата'), (2, 'Прибуток')], decimal_places=0, default=1, max_digits=1),
        ),
    ]
