# Generated by Django 2.1.4 on 2018-12-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbleapp', '0003_auto_20181231_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction',
            new_name='trans',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
